---
- hosts: localhost
  connection: local

  vars:
    cran_mirror: "http://r.meteo.uni.wroc.pl"
    rstudio_version: 0.99.891

  roles:
    - role: nuada.dockerize
      timezone: "Europe/Warsaw"

  tasks:
    - name: install Ubuntu CRAN key
      apt_key: keyserver=keyserver.ubuntu.com id=E084DAB9

    - name: setup CRAN apt repo
      copy: dest=/etc/apt/sources.list.d/cran.list
        content="deb {{ cran_mirror }}/bin/linux/ubuntu {{ ansible_lsb.codename }}/"

    - name: group omicron
      group: name=omicron gid=1000

    - name: default user
      user: name=omicron uid=1000 group=omicron groups=sudo shell=/bin/bash

    - name: ssh dir
      file: path=/home/omicron/.ssh state=directory
         owner=omicron group=omicron mode=0700

    - name: allow omicron user to use passwordless sudo
      copy: dest=/etc/sudoers.d/90-omicron content="omicron ALL=(ALL) NOPASSWD:ALL"
        owner=root group=root mode=0440

    - name: install packages
      apt: name={{ item }}
      with_items:
        - bedtools
        - bowtie2
        - bsdmainutils
        - build-essential
        - bwa
        - byobu
        - curl
        - fastqc
        - git
        - ipython
        - lbzip2
        - libgsl0ldbl
        - munge
        - ncbi-blast+
        - openjdk-7-jre-headless
        - picard-tools
        - python-dev
        - python-pip
        - samtools
        - slurm-llnl
        - sqlite3
        - trimmomatic
        - unzip
        - vcftools
        - vim
        - wget
        - zlib1g-dev
        - gdebi-core
        - openjdk-7-jdk
        - plink
        - psmisc
        - python-pandas
        - r-base
        - r-base-dev
        - r-cran-rjava

    - name: install R dependecies from CRAN
      command: /usr/bin/Rscript -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) install.packages('{{ item }}', repo=c('{{ cran_mirror }}'))"
      with_items:
        - ggplot2
        - lubridate
        - plyr
        - reshape2
        - xlsx

    - name: install printr
      command: /usr/bin/Rscript -e "if (! ('{{ item }}' %in% installed.packages()[,'Package'])) install.packages('{{ item }}', repo=c('http://yihui.name/xran', '{{ cran_mirror }}'))"
      with_items:
        - printr

    - name: install cutadapt
      pip: name={{ item }}
      with_items:
        - cutadapt
        - data_hacks
        - illuminate

    - name: ea-utils install prerequisites
      apt: name={{ item }}
      with_items:
        - libgsl0-dev
        - subversion
    
    - name: ea-utils checkout source
      subversion: repo=http://ea-utils.googlecode.com/svn/trunk/ dest=/tmp/ansible/ea-utils
    
    - name: ea-utils compile and install
      shell: make && make install chdir=/tmp/ansible/ea-utils/clipper

    - name: install skewer
      get_url: url=http://sourceforge.net/projects/skewer/files/Binaries/skewer-0.2.0-linux-x86_64/download
        dest=/usr/bin/skewer owner=root group=root mode=0755
    
    - name: create temp dir
      file: path=/tmp/ansible state=directory

    # Install bcftools
    - git: repo=git://github.com/samtools/htslib.git dest=/tmp/ansible/htslib accept_hostkey=yes
    - git: repo=git://github.com/samtools/bcftools.git dest=/tmp/ansible/bcftools accept_hostkey=yes
    - shell: make -j{{ ansible_processor_vcpus }} chdir=/tmp/ansible/htslib
    - shell: make -j{{ ansible_processor_vcpus }} && mv bcftools /usr/bin chdir=/tmp/ansible/bcftools

    # Install plink
    - shell: wget "https://www.cog-genomics.org$(curl -s https://www.cog-genomics.org/plink2/ | grep -Eo '/static/bin/plink[0-9]{6}/plink_linux_x86_64.zip')" &&
        unzip plink_linux_x86_64.zip && mv plink /usr/bin chdir=/tmp/ansible

    # Install GEMINI
    - get_url: url=https://raw.github.com/arq5x/gemini/master/gemini/scripts/gemini_install.py
        dest=/tmp/ansible/gemini_install.py owner=root group=root mode=0755
    - shell: python gemini_install.py --nodata /usr /usr/share/gemini chdir=/tmp/ansible
    - lineinfile: "dest=/usr/share/gemini/gemini-config.yaml regexp='^annotation_dir: ' line='annotation_dir: /resources/gemini/data'"

    # Install vt
    - git: repo=git://github.com/atks/vt.git dest=/tmp/ansible/vt accept_hostkey=yes
    - shell: make -j{{ ansible_processor_vcpus }} && mv vt /usr/bin chdir=/tmp/ansible/vt

    - name: download RStudio Server
      get_url:
        url="http://download2.rstudio.org/rstudio-server-{{ rstudio_version }}-amd64.deb"
        dest="/tmp/ansible/rstudio-server-{{ rstudio_version }}-amd64.deb"

    - name: install RStudio Server
      apt: deb="/tmp/ansible/rstudio-server-{{ rstudio_version }}-amd64.deb"

    - name: install king
      shell: curl http://people.virginia.edu/~wc9c/KING/Linux-king.tar.gz | tar zx -C /usr/bin

    - name: install EIGENSTAT
      shell: curl https://codeload.github.com/DReichLab/EIG/tar.gz/master | tar zx -C /usr/bin --wildcards '*/bin/*' --strip-components=2

    - name: install impute2
      shell: curl https://mathgen.stats.ox.ac.uk/impute/impute_v2.3.2_x86_64_dynamic.tgz | tar zx -C /usr/bin --wildcards '*/impute2' --strip-components=1

    - name: install gtool
      shell: curl http://www.well.ox.ac.uk/~cfreeman/software/gwas/gtool_v0.7.5_x86_64_dynamic.tgz | tar zx -C /usr/bin gtool

    - name: install snptest
      shell: curl http://www.well.ox.ac.uk/~gav/resources/snptest_v2.5.1_linux_x86_64_dynamic.tgz | tar zx -C /usr/bin --wildcards '*/snptest*' --strip-components=1

    - name: install qctool
      shell: curl http://www.well.ox.ac.uk/~gav/qctool/resources/qctool_v1.4-linux-x86_64.tgz | tar zx -C /usr/bin --wildcards '*/qctool' --strip-components=1

    - name: install beelinetools
      shell: curl https://codeload.github.com/pgxcentre/beelinetools/tar.gz/0.2.2 | tar zx -C /usr/bin --wildcards '*/beelinetools.py' --strip-components=1

    - name: install csvkit
      pip: name=csvkit

    # Setup munge & slurm
    - name: check munge key
      stat: path=/etc/munge/munge.key
      register: munge_key

    - name: create munge key
      command: /usr/sbin/create-munge-key
      when: not munge_key.stat.exists

    - name: fix munge defaults
      lineinfile: dest=/etc/default/munge regexp=^OPTIONS= line=OPTIONS="--syslog"

    - name: configure slurm
      template: src=/etc/ansible/slurm.conf.j2 dest=/etc/slurm-llnl/slurm.conf
        owner=root group=root mode=0644

    - name: cleanup temp
      file: path=/tmp/ansible state=absent
